version: '3.6'
services:
  postgres:
    image: postgres:12
    container_name: kfx-postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  rails-backend:
    build: backend-rails/docker
    container_name: kfx-rails
    depends_on:
      - "postgres"
    working_dir: /application
    restart: always
    volumes: 
      - ./backend-rails:/application
    ports:
      - "3000:3000"
    environment:
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
volumes:
  db_data:

