version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.13.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: $H_ADMIN_PWD
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "RS256", "key": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuZDwi3VRzDqqi34W+dt5\n8aI3Z9LYbvCGJ1WvSy6/0PYanSNbHSa20yH11Ietj8g2g8DK1YZvLHfdzgLiT7Qq\nQMi04tCYsfh48Pf18yyQxfM/ltEmx4eE+uckcjG8nenajLSo3g3eGI+z+isQCfWy\nWBz7ZZRoGG5YLv7fuTA7hKnpt4toML72kjOWSwZ1V2t2s5lUuXbWvnMgxXvaI/A6\n2S7Zhu8ZV6CRBthMirQ0sbwn0yhntxFaNKAmOHfPq562aj0v9NauuzueHcrU/sJj\nlYKlt6xBnRYUaJd+T2+MW7SbyizE3WwPaW4GktH9ny7hA6qRLVANpcTmpzntcsaK\n04r+4PD8vujowIejz3uyLFFuBEzNxM0LFchvqt89rHS7O+4h7WHf2rpvgFe75wYe\n/JwxmTJQ+UkFb5YraPvqni7/i+qZsPbZO5DOBTTTLYzUK3XLWUnbJ4X728mug0HP\nCJGnQPs8aZuKT6lWh9+efGvFEhb7KIGOL2E+ULbTtLPJacmsx8YGNebU9z8hldd+\nC5YPvRGn3dnM9iH6GM/Q5UNs/yZQQYQH1eLl9gHBkgeBIWxSwldpckk8UDLHX3gY\nEeffv/r25BMhvHZ8t+srDFqui+60Ue4keb0YN8B/T5qfi6EI+dpq7PIqAWjwufsb\n42c9s5g+GjKSOlEWMdy5G8kCAwEAAQ==\n-----END PUBLIC KEY-----\n", "header": {"type": "Cookie", "name": "hasuraaccess" } }'      
  webserver:
    image: nginx:alpine
    container_name: backend-webserver
    working_dir: /application
    restart: always
    volumes:
        - ./backend:/application
        - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "2222:80"
  backend:
    build: backend/docker
    container_name: backend-php-fpm
    working_dir: /application
    restart: always
    volumes:
      - ./backend:/application
      #- upload_data:/uploads
      #- ./uploads:/uploads
      - ./backend/docker/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: $H_ADMIN_PWD
      HASURA_GRAPHQL_JWT_SECRET: $H_JWT_SECRET
      HASURA_API: http://graphql-engine:8080/v1/graphql
volumes:
  db_data:

